
python: 3.7

branches:
  only:
    - master

before_install:
  - "./.travis/install.sh"


# see macOS version https://docs.travis-ci.com/user/reference/osx/#os-x-version

matrix:
  include:
  - os: osx
    osx_image: xcode9.4  # 10.13
    language: generic
    script:
    - "./.travis/tests.sh"


after_success:
  - codecov
